//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Connectone.Asset_Locations {
    using System.Xml.Serialization;
    
    
   
    public partial class GetClientAuthorizations {
        
        private string taskField;
        
        private string permissionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Task {
            get {
                return this.taskField;
            }
            set {
                this.taskField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Permission {
            get {
                return this.permissionField;
            }
            set {
                this.permissionField = value;
            }
        }
    }
    

    public partial class GetFullList {
        
        private string locationNameField;
        
        private string otherDetailField;
        
        private string systemField;
        
        private string idField;
        
        private string matchedTypeField;
        
        private string matchedNameField;
        
        private string matchedInsttField;
        
        private int yEARIDField;
        
        private bool yEARIDFieldSpecified;
        
        private string oRG_RECField;
        
        private string addByField;
        
        private System.DateTime addDateField;
        
        private bool addDateFieldSpecified;
        
        private string editByField;
        
        private System.DateTime editDateField;
        
        private bool editDateFieldSpecified;
        
        private string actionStatusField;
        
        private string actionByField;
        
        private System.DateTime actionDateField;
        
        private bool actionDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Location Name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LocationName {
            get {
                return this.locationNameField;
            }
            set {
                this.locationNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Other Detail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OtherDetail {
            get {
                return this.otherDetailField;
            }
            set {
                this.otherDetailField = value;
            }
        }
        
       /// <summary>
        /// This field has been renamed from "System" to "SystemName" as the earlier one is a Keyword
       /// </summary>
        public string SystemName {
            get {
                return this.systemField;
            }
            set {
                this.systemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Matched Type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MatchedType {
            get {
                return this.matchedTypeField;
            }
            set {
                this.matchedTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Matched Name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MatchedName {
            get {
                return this.matchedNameField;
            }
            set {
                this.matchedNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Matched Instt.", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MatchedInstt {
            get {
                return this.matchedInsttField;
            }
            set {
                this.matchedInsttField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int YEARID {
            get {
                return this.yEARIDField;
            }
            set {
                this.yEARIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool YEARIDSpecified {
            get {
                return this.yEARIDFieldSpecified;
            }
            set {
                this.yEARIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ORG_REC {
            get {
                return this.oRG_RECField;
            }
            set {
                this.oRG_RECField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Add By", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddBy {
            get {
                return this.addByField;
            }
            set {
                this.addByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Add Date", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime AddDate {
            get {
                return this.addDateField;
            }
            set {
                this.addDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AddDateSpecified {
            get {
                return this.addDateFieldSpecified;
            }
            set {
                this.addDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Edit By", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EditBy {
            get {
                return this.editByField;
            }
            set {
                this.editByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Edit Date", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime EditDate {
            get {
                return this.editDateField;
            }
            set {
                this.editDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EditDateSpecified {
            get {
                return this.editDateFieldSpecified;
            }
            set {
                this.editDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Action Status", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ActionStatus {
            get {
                return this.actionStatusField;
            }
            set {
                this.actionStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Action By", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ActionBy {
            get {
                return this.actionByField;
            }
            set {
                this.actionByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Action Date", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime ActionDate {
            get {
                return this.actionDateField;
            }
            set {
                this.actionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionDateSpecified {
            get {
                return this.actionDateFieldSpecified;
            }
            set {
                this.actionDateFieldSpecified = value;
            }
        }
    }
    
   
    public partial class GetList {
        
        private string locationNameField;
        
        private string aL_IDField;
        
        private System.DateTime rEC_EDIT_ONField;
        
        private bool rEC_EDIT_ONFieldSpecified;
        
        private string matchedTypeField;
        
        private string matchedNameField;
        
        private string matchedInsttField;
        
        private decimal final_AmountField;
        
        private bool final_AmountFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Location Name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LocationName {
            get {
                return this.locationNameField;
            }
            set {
                this.locationNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AL_ID {
            get {
                return this.aL_IDField;
            }
            set {
                this.aL_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime REC_EDIT_ON {
            get {
                return this.rEC_EDIT_ONField;
            }
            set {
                this.rEC_EDIT_ONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REC_EDIT_ONSpecified {
            get {
                return this.rEC_EDIT_ONFieldSpecified;
            }
            set {
                this.rEC_EDIT_ONFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Matched Type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MatchedType {
            get {
                return this.matchedTypeField;
            }
            set {
                this.matchedTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Matched Name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MatchedName {
            get {
                return this.matchedNameField;
            }
            set {
                this.matchedNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Matched Instt.", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MatchedInstt {
            get {
                return this.matchedInsttField;
            }
            set {
                this.matchedInsttField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Final_Amount {
            get {
                return this.final_AmountField;
            }
            set {
                this.final_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Final_AmountSpecified {
            get {
                return this.final_AmountFieldSpecified;
            }
            set {
                this.final_AmountFieldSpecified = value;
            }
        }
    }
    
   
    public partial class GetListByCenID {
        
        private string locationNameField;
        
        private string aL_IDField;
        
        private System.DateTime rEC_EDIT_ONField;
        
        private bool rEC_EDIT_ONFieldSpecified;
        
        private string matchedTypeField;
        
        private string matchedNameField;
        
        private string matchedInsttField;
        
        private decimal final_AmountField;
        
        private bool final_AmountFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Location Name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LocationName {
            get {
                return this.locationNameField;
            }
            set {
                this.locationNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AL_ID {
            get {
                return this.aL_IDField;
            }
            set {
                this.aL_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime REC_EDIT_ON {
            get {
                return this.rEC_EDIT_ONField;
            }
            set {
                this.rEC_EDIT_ONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REC_EDIT_ONSpecified {
            get {
                return this.rEC_EDIT_ONFieldSpecified;
            }
            set {
                this.rEC_EDIT_ONFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Matched Type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MatchedType {
            get {
                return this.matchedTypeField;
            }
            set {
                this.matchedTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Matched Name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MatchedName {
            get {
                return this.matchedNameField;
            }
            set {
                this.matchedNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Matched Instt.", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MatchedInstt {
            get {
                return this.matchedInsttField;
            }
            set {
                this.matchedInsttField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Final_Amount {
            get {
                return this.final_AmountField;
            }
            set {
                this.final_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Final_AmountSpecified {
            get {
                return this.final_AmountFieldSpecified;
            }
            set {
                this.final_AmountFieldSpecified = value;
            }
        }
    }
    
   
    public partial class GetListByLBID {
        
        private string aL_IDField;
        
        private System.DateTime rEC_EDIT_ONField;
        
        private bool rEC_EDIT_ONFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AL_ID {
            get {
                return this.aL_IDField;
            }
            set {
                this.aL_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime REC_EDIT_ON {
            get {
                return this.rEC_EDIT_ONField;
            }
            set {
                this.rEC_EDIT_ONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REC_EDIT_ONSpecified {
            get {
                return this.rEC_EDIT_ONFieldSpecified;
            }
            set {
                this.rEC_EDIT_ONFieldSpecified = value;
            }
        }
    }
    
   
    public partial class GetListBySPID {
        
        private string aL_IDField;
        
        private string aL_LOC_NAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AL_ID {
            get {
                return this.aL_IDField;
            }
            set {
                this.aL_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AL_LOC_NAME {
            get {
                return this.aL_LOC_NAMEField;
            }
            set {
                this.aL_LOC_NAMEField = value;
            }
        }
    }
    
   
    public partial class GetLocationMapping {
        
        private long srField;
        
        private bool srFieldSpecified;
        
        private string instituteField;
        
        private string uIDField;
        
        private string locationNameField;
        
        private string locationRemarksField;
        
        private string matchedTypeField;
        
        private string propertyNameField;
        
        private string propertyAddressField;
        
        private string propertyCategoryField;
        
        private string propertyTypeField;
        
        private string propertyUseField;
        
        private string propertyInsttField;
        
        private string proIDField;
        
        private string propertyStatusField;
        
        private string servicePlaceNameField;
        
        private string servicePlaceTypeField;
        
        private string servicePlaceInsttField;
        
        private string serIDField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Sr.", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long Sr {
            get {
                return this.srField;
            }
            set {
                this.srField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SrSpecified {
            get {
                return this.srFieldSpecified;
            }
            set {
                this.srFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Institute {
            get {
                return this.instituteField;
            }
            set {
                this.instituteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UID {
            get {
                return this.uIDField;
            }
            set {
                this.uIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Location Name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LocationName {
            get {
                return this.locationNameField;
            }
            set {
                this.locationNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Location Remarks", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LocationRemarks {
            get {
                return this.locationRemarksField;
            }
            set {
                this.locationRemarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Matched Type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MatchedType {
            get {
                return this.matchedTypeField;
            }
            set {
                this.matchedTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Property Name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PropertyName {
            get {
                return this.propertyNameField;
            }
            set {
                this.propertyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Property Address", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PropertyAddress {
            get {
                return this.propertyAddressField;
            }
            set {
                this.propertyAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Property Category", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PropertyCategory {
            get {
                return this.propertyCategoryField;
            }
            set {
                this.propertyCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Property Type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PropertyType {
            get {
                return this.propertyTypeField;
            }
            set {
                this.propertyTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Property Use", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PropertyUse {
            get {
                return this.propertyUseField;
            }
            set {
                this.propertyUseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Property Instt", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PropertyInstt {
            get {
                return this.propertyInsttField;
            }
            set {
                this.propertyInsttField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Pro.ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProID {
            get {
                return this.proIDField;
            }
            set {
                this.proIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Property Status", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PropertyStatus {
            get {
                return this.propertyStatusField;
            }
            set {
                this.propertyStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Service Place Name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServicePlaceName {
            get {
                return this.servicePlaceNameField;
            }
            set {
                this.servicePlaceNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Service Place Type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServicePlaceType {
            get {
                return this.servicePlaceTypeField;
            }
            set {
                this.servicePlaceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Service Place Instt", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServicePlaceInstt {
            get {
                return this.servicePlaceInsttField;
            }
            set {
                this.servicePlaceInsttField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Ser.ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SerID {
            get {
                return this.serIDField;
            }
            set {
                this.serIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
   
    public partial class GetRecord {
        
        private int aL_CEN_IDField;
        
        private bool aL_CEN_IDFieldSpecified;
        
        private string aL_LOC_NAMEField;
        
        private string aL_OTHER_DETAILField;
        
        private string aL_LOC_MAINField;
        
        private System.DateTime rEC_ADD_ONField;
        
        private bool rEC_ADD_ONFieldSpecified;
        
        private string rEC_ADD_BYField;
        
        private System.DateTime rEC_EDIT_ONField;
        
        private bool rEC_EDIT_ONFieldSpecified;
        
        private string rEC_EDIT_BYField;
        
        private int rEC_STATUSField;
        
        private bool rEC_STATUSFieldSpecified;
        
        private System.DateTime rEC_STATUS_ONField;
        
        private bool rEC_STATUS_ONFieldSpecified;
        
        private string rEC_STATUS_BYField;
        
        private string rEC_IDField;
        
        private string lB_REC_IDField;
        
        private string sP_REC_IDField;
        
        private string aL_ORG_REC_IDField;
        
        private int aL_COD_YEAR_IDField;
        
        private bool aL_COD_YEAR_IDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int AL_CEN_ID {
            get {
                return this.aL_CEN_IDField;
            }
            set {
                this.aL_CEN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AL_CEN_IDSpecified {
            get {
                return this.aL_CEN_IDFieldSpecified;
            }
            set {
                this.aL_CEN_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AL_LOC_NAME {
            get {
                return this.aL_LOC_NAMEField;
            }
            set {
                this.aL_LOC_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AL_OTHER_DETAIL {
            get {
                return this.aL_OTHER_DETAILField;
            }
            set {
                this.aL_OTHER_DETAILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AL_LOC_MAIN {
            get {
                return this.aL_LOC_MAINField;
            }
            set {
                this.aL_LOC_MAINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime REC_ADD_ON {
            get {
                return this.rEC_ADD_ONField;
            }
            set {
                this.rEC_ADD_ONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REC_ADD_ONSpecified {
            get {
                return this.rEC_ADD_ONFieldSpecified;
            }
            set {
                this.rEC_ADD_ONFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REC_ADD_BY {
            get {
                return this.rEC_ADD_BYField;
            }
            set {
                this.rEC_ADD_BYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime REC_EDIT_ON {
            get {
                return this.rEC_EDIT_ONField;
            }
            set {
                this.rEC_EDIT_ONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REC_EDIT_ONSpecified {
            get {
                return this.rEC_EDIT_ONFieldSpecified;
            }
            set {
                this.rEC_EDIT_ONFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REC_EDIT_BY {
            get {
                return this.rEC_EDIT_BYField;
            }
            set {
                this.rEC_EDIT_BYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int REC_STATUS {
            get {
                return this.rEC_STATUSField;
            }
            set {
                this.rEC_STATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REC_STATUSSpecified {
            get {
                return this.rEC_STATUSFieldSpecified;
            }
            set {
                this.rEC_STATUSFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime REC_STATUS_ON {
            get {
                return this.rEC_STATUS_ONField;
            }
            set {
                this.rEC_STATUS_ONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REC_STATUS_ONSpecified {
            get {
                return this.rEC_STATUS_ONFieldSpecified;
            }
            set {
                this.rEC_STATUS_ONFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REC_STATUS_BY {
            get {
                return this.rEC_STATUS_BYField;
            }
            set {
                this.rEC_STATUS_BYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REC_ID {
            get {
                return this.rEC_IDField;
            }
            set {
                this.rEC_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LB_REC_ID {
            get {
                return this.lB_REC_IDField;
            }
            set {
                this.lB_REC_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SP_REC_ID {
            get {
                return this.sP_REC_IDField;
            }
            set {
                this.sP_REC_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AL_ORG_REC_ID {
            get {
                return this.aL_ORG_REC_IDField;
            }
            set {
                this.aL_ORG_REC_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int AL_COD_YEAR_ID {
            get {
                return this.aL_COD_YEAR_IDField;
            }
            set {
                this.aL_COD_YEAR_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AL_COD_YEAR_IDSpecified {
            get {
                return this.aL_COD_YEAR_IDFieldSpecified;
            }
            set {
                this.aL_COD_YEAR_IDFieldSpecified = value;
            }
        }
    }
}
