//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Connectone.Center {
    using System.Xml.Serialization;
    
    
    public partial class AddInsuranceVerification {
        
        private int column1Field;
        
        private bool column1FieldSpecified;
        
        /// <remarks/>
        
        public int Column1 {
            get {
                return this.column1Field;
            }
            set {
                this.column1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Column1Specified {
            get {
                return this.column1FieldSpecified;
            }
            set {
                this.column1FieldSpecified = value;
            }
        }
    }
    
   
    public partial class Client_Audit_Info {
        
        private string gradeField;
        
        private string reasonField;
        
        /// <remarks/>
        
        public string Grade {
            get {
                return this.gradeField;
            }
            set {
                this.gradeField = value;
            }
        }
        
        /// <remarks/>
        
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
    }
    
   
    public partial class GetAccountsSubmissionReport {
        
        private string monthSubmittedField;
        
        private System.DateTime dateofFirstSubmissionField;
        
        private bool dateofFirstSubmissionFieldSpecified;
        
        private System.DateTime dateofLastSubmissionField;
        
        private bool dateofLastSubmissionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Month Submitted", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MonthSubmitted {
            get {
                return this.monthSubmittedField;
            }
            set {
                this.monthSubmittedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Date of First Submission", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DateofFirstSubmission {
            get {
                return this.dateofFirstSubmissionField;
            }
            set {
                this.dateofFirstSubmissionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateofFirstSubmissionSpecified {
            get {
                return this.dateofFirstSubmissionFieldSpecified;
            }
            set {
                this.dateofFirstSubmissionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Date of Last Submission", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DateofLastSubmission {
            get {
                return this.dateofLastSubmissionField;
            }
            set {
                this.dateofLastSubmissionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateofLastSubmissionSpecified {
            get {
                return this.dateofLastSubmissionFieldSpecified;
            }
            set {
                this.dateofLastSubmissionFieldSpecified = value;
            }
        }
    }
    
 
    public partial class GetAccountsSubmittedPeriod {
        
        private System.DateTime cSA_SUBMIT_FROMField;
        
        private bool cSA_SUBMIT_FROMFieldSpecified;
        
        private System.DateTime cSA_SUBMIT_TOField;
        
        private bool cSA_SUBMIT_TOFieldSpecified;
        
        private System.DateTime cSA_SUBMIT_ONField;
        
        private bool cSA_SUBMIT_ONFieldSpecified;
        
        private string cSA_SUBMIT_BYField;
        
        /// <remarks/>
        
        public System.DateTime CSA_SUBMIT_FROM {
            get {
                return this.cSA_SUBMIT_FROMField;
            }
            set {
                this.cSA_SUBMIT_FROMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CSA_SUBMIT_FROMSpecified {
            get {
                return this.cSA_SUBMIT_FROMFieldSpecified;
            }
            set {
                this.cSA_SUBMIT_FROMFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public System.DateTime CSA_SUBMIT_TO {
            get {
                return this.cSA_SUBMIT_TOField;
            }
            set {
                this.cSA_SUBMIT_TOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CSA_SUBMIT_TOSpecified {
            get {
                return this.cSA_SUBMIT_TOFieldSpecified;
            }
            set {
                this.cSA_SUBMIT_TOFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public System.DateTime CSA_SUBMIT_ON {
            get {
                return this.cSA_SUBMIT_ONField;
            }
            set {
                this.cSA_SUBMIT_ONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CSA_SUBMIT_ONSpecified {
            get {
                return this.cSA_SUBMIT_ONFieldSpecified;
            }
            set {
                this.cSA_SUBMIT_ONFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public string CSA_SUBMIT_BY {
            get {
                return this.cSA_SUBMIT_BYField;
            }
            set {
                this.cSA_SUBMIT_BYField = value;
            }
        }
    }
    
   
    public partial class GetAuditPeriod {
        
        private System.DateTime hE_TNXS_FROMField;
        
        private bool hE_TNXS_FROMFieldSpecified;
        
        private System.DateTime hE_TOField;
        
        private bool hE_TOFieldSpecified;
        
        /// <remarks/>
        
        public System.DateTime HE_TNXS_FROM {
            get {
                return this.hE_TNXS_FROMField;
            }
            set {
                this.hE_TNXS_FROMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HE_TNXS_FROMSpecified {
            get {
                return this.hE_TNXS_FROMFieldSpecified;
            }
            set {
                this.hE_TNXS_FROMFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public System.DateTime HE_TO {
            get {
                return this.hE_TOField;
            }
            set {
                this.hE_TOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HE_TOSpecified {
            get {
                return this.hE_TOFieldSpecified;
            }
            set {
                this.hE_TOFieldSpecified = value;
            }
        }
    }
    
   
    public partial class GetAuditTxnPeriod {
        
        private System.DateTime fROMField;
        
        private bool fROMFieldSpecified;
        
        private System.DateTime toField;
        
        private bool toFieldSpecified;
        
        /// <remarks/>
        
        public System.DateTime FROM {
            get {
                return this.fROMField;
            }
            set {
                this.fROMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FROMSpecified {
            get {
                return this.fROMFieldSpecified;
            }
            set {
                this.fROMFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public System.DateTime TO {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TOSpecified {
            get {
                return this.toFieldSpecified;
            }
            set {
                this.toFieldSpecified = value;
            }
        }
    }
    
   
    public partial class GetCenterDetailsByCertNo {
        
        private string cEN_NAMEField;
        
        private string cEN_CON_SCANCODEField;
        
        private string uIDField;
        
        private string rEG_NOField;
        
        private string cEN_B_NAMEField;
        
        private string cEN_ADD1Field;
        
        private string cEN_ADD2Field;
        
        private string cEN_ADD3Field;
        
        private string cEN_ADD4Field;
        
        private string cEN_CITYField;
        
        private string cEN_STATEField;
        
        private string cEN_COUNTRYField;
        
        private string cEN_INCHARGEField;
        
        /// <remarks/>
        
        public string CEN_NAME {
            get {
                return this.cEN_NAMEField;
            }
            set {
                this.cEN_NAMEField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_CON_SCANCODE {
            get {
                return this.cEN_CON_SCANCODEField;
            }
            set {
                this.cEN_CON_SCANCODEField = value;
            }
        }
        
        /// <remarks/>
        
        public string UID {
            get {
                return this.uIDField;
            }
            set {
                this.uIDField = value;
            }
        }
        
        /// <remarks/>
        
        public string REG_NO {
            get {
                return this.rEG_NOField;
            }
            set {
                this.rEG_NOField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_B_NAME {
            get {
                return this.cEN_B_NAMEField;
            }
            set {
                this.cEN_B_NAMEField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_ADD1 {
            get {
                return this.cEN_ADD1Field;
            }
            set {
                this.cEN_ADD1Field = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_ADD2 {
            get {
                return this.cEN_ADD2Field;
            }
            set {
                this.cEN_ADD2Field = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_ADD3 {
            get {
                return this.cEN_ADD3Field;
            }
            set {
                this.cEN_ADD3Field = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_ADD4 {
            get {
                return this.cEN_ADD4Field;
            }
            set {
                this.cEN_ADD4Field = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_CITY {
            get {
                return this.cEN_CITYField;
            }
            set {
                this.cEN_CITYField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_STATE {
            get {
                return this.cEN_STATEField;
            }
            set {
                this.cEN_STATEField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_COUNTRY {
            get {
                return this.cEN_COUNTRYField;
            }
            set {
                this.cEN_COUNTRYField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_INCHARGE {
            get {
                return this.cEN_INCHARGEField;
            }
            set {
                this.cEN_INCHARGEField = value;
            }
        }
    }
    
    
    public partial class GetCenterListByAuditor_Instt {
        
        private string cEN_UIDField;
        
        private string cEN_PAD_NOField;
        
        private string cEN_NAMEField;
        
        private int cEN_IDField;
        
        private bool cEN_IDFieldSpecified;
        
        private string rEC_IDField;
        
        private string cEN_ZONE_IDField;
        
        private string cEN_ZONE_SUB_IDField;
        
        private string cEN_ACC_TYPE_IDField;
        
        private int cOD_YEAR_IDField;
        
        private bool cOD_YEAR_IDFieldSpecified;
        
        private string cOD_YEAR_NAMEField;
        
        private System.DateTime cOD_YEAR_SDTField;
        
        private bool cOD_YEAR_SDTFieldSpecified;
        
        private System.DateTime cOD_YEAR_EDTField;
        
        private bool cOD_YEAR_EDTFieldSpecified;
        
        private int cEN_ID_MAINField;
        
        private bool cEN_ID_MAINFieldSpecified;
        
        private string cEN_PAD_NO_MAINField;
        
        private string auditStatusField;
        
        private int iS_VOLUMEField;
        
        private bool iS_VOLUMEFieldSpecified;
        
        /// <remarks/>
        
        public string CEN_UID {
            get {
                return this.cEN_UIDField;
            }
            set {
                this.cEN_UIDField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_PAD_NO {
            get {
                return this.cEN_PAD_NOField;
            }
            set {
                this.cEN_PAD_NOField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_NAME {
            get {
                return this.cEN_NAMEField;
            }
            set {
                this.cEN_NAMEField = value;
            }
        }
        
        /// <remarks/>
        
        public int CEN_ID {
            get {
                return this.cEN_IDField;
            }
            set {
                this.cEN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CEN_IDSpecified {
            get {
                return this.cEN_IDFieldSpecified;
            }
            set {
                this.cEN_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public string REC_ID {
            get {
                return this.rEC_IDField;
            }
            set {
                this.rEC_IDField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_ZONE_ID {
            get {
                return this.cEN_ZONE_IDField;
            }
            set {
                this.cEN_ZONE_IDField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_ZONE_SUB_ID {
            get {
                return this.cEN_ZONE_SUB_IDField;
            }
            set {
                this.cEN_ZONE_SUB_IDField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_ACC_TYPE_ID {
            get {
                return this.cEN_ACC_TYPE_IDField;
            }
            set {
                this.cEN_ACC_TYPE_IDField = value;
            }
        }
        
        /// <remarks/>
        
        public int COD_YEAR_ID {
            get {
                return this.cOD_YEAR_IDField;
            }
            set {
                this.cOD_YEAR_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool COD_YEAR_IDSpecified {
            get {
                return this.cOD_YEAR_IDFieldSpecified;
            }
            set {
                this.cOD_YEAR_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public string COD_YEAR_NAME {
            get {
                return this.cOD_YEAR_NAMEField;
            }
            set {
                this.cOD_YEAR_NAMEField = value;
            }
        }
        
        /// <remarks/>
        
        public System.DateTime COD_YEAR_SDT {
            get {
                return this.cOD_YEAR_SDTField;
            }
            set {
                this.cOD_YEAR_SDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool COD_YEAR_SDTSpecified {
            get {
                return this.cOD_YEAR_SDTFieldSpecified;
            }
            set {
                this.cOD_YEAR_SDTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public System.DateTime COD_YEAR_EDT {
            get {
                return this.cOD_YEAR_EDTField;
            }
            set {
                this.cOD_YEAR_EDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool COD_YEAR_EDTSpecified {
            get {
                return this.cOD_YEAR_EDTFieldSpecified;
            }
            set {
                this.cOD_YEAR_EDTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public int CEN_ID_MAIN {
            get {
                return this.cEN_ID_MAINField;
            }
            set {
                this.cEN_ID_MAINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CEN_ID_MAINSpecified {
            get {
                return this.cEN_ID_MAINFieldSpecified;
            }
            set {
                this.cEN_ID_MAINFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_PAD_NO_MAIN {
            get {
                return this.cEN_PAD_NO_MAINField;
            }
            set {
                this.cEN_PAD_NO_MAINField = value;
            }
        }
        
        /// <remarks/>
        
        public string AuditStatus {
            get {
                return this.auditStatusField;
            }
            set {
                this.auditStatusField = value;
            }
        }
        
        /// <remarks/>
        
        public int IS_VOLUME {
            get {
                return this.iS_VOLUMEField;
            }
            set {
                this.iS_VOLUMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IS_VOLUMESpecified {
            get {
                return this.iS_VOLUMEFieldSpecified;
            }
            set {
                this.iS_VOLUMEFieldSpecified = value;
            }
        }
    }
    
   
    public partial class GetCenterListByBKCertNo {
        
        private string iNS_NAMEField;
        
        private string cEN_INS_IDField;
        
        private int cEN_IDField;
        
        private bool cEN_IDFieldSpecified;
        
        private string cEN_PAD_NOField;
        
        private string cEN_UIDField;
        
        private string cREATION_STATUSField;
        
        private string passwordField;
        
        /// <remarks/>
        
        public string INS_NAME {
            get {
                return this.iNS_NAMEField;
            }
            set {
                this.iNS_NAMEField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_INS_ID {
            get {
                return this.cEN_INS_IDField;
            }
            set {
                this.cEN_INS_IDField = value;
            }
        }
        
        /// <remarks/>
        
        public int CEN_ID {
            get {
                return this.cEN_IDField;
            }
            set {
                this.cEN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CEN_IDSpecified {
            get {
                return this.cEN_IDFieldSpecified;
            }
            set {
                this.cEN_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_PAD_NO {
            get {
                return this.cEN_PAD_NOField;
            }
            set {
                this.cEN_PAD_NOField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_UID {
            get {
                return this.cEN_UIDField;
            }
            set {
                this.cEN_UIDField = value;
            }
        }
        
        /// <remarks/>
        
        public string CREATION_STATUS {
            get {
                return this.cREATION_STATUSField;
            }
            set {
                this.cREATION_STATUSField = value;
            }
        }
        
        /// <remarks/>
        
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
   
    public partial class GetCenterListByCenID {
        
        private string cEN_UIDField;
        
        private string cEN_PAD_NOField;
        
        private string cEN_NAMEField;
        
        private int cEN_IDField;
        
        private bool cEN_IDFieldSpecified;
        
        private string rEC_IDField;
        
        private string cEN_ZONE_IDField;
        
        private string cEN_ZONE_SUB_IDField;
        
        private string cEN_ACC_TYPE_IDField;
        
        private int cOD_YEAR_IDField;
        
        private bool cOD_YEAR_IDFieldSpecified;
        
        private string cOD_YEAR_NAMEField;
        
        private System.DateTime cOD_YEAR_SDTField;
        
        private bool cOD_YEAR_SDTFieldSpecified;
        
        private System.DateTime cOD_YEAR_EDTField;
        
        private bool cOD_YEAR_EDTFieldSpecified;
        
        private int cEN_ID_MAINField;
        
        private bool cEN_ID_MAINFieldSpecified;
        
        private string cEN_PAD_NO_MAINField;
        
        private string cEN_INS_IDField;
        
        private string iNS_NAMEField;
        
        private string iNS_SHORTField;
        
        private int iS_VOLUMEField;
        
        private bool iS_VOLUMEFieldSpecified;
        
        /// <remarks/>
        
        public string CEN_UID {
            get {
                return this.cEN_UIDField;
            }
            set {
                this.cEN_UIDField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_PAD_NO {
            get {
                return this.cEN_PAD_NOField;
            }
            set {
                this.cEN_PAD_NOField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_NAME {
            get {
                return this.cEN_NAMEField;
            }
            set {
                this.cEN_NAMEField = value;
            }
        }
        
        /// <remarks/>
        
        public int CEN_ID {
            get {
                return this.cEN_IDField;
            }
            set {
                this.cEN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CEN_IDSpecified {
            get {
                return this.cEN_IDFieldSpecified;
            }
            set {
                this.cEN_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public string REC_ID {
            get {
                return this.rEC_IDField;
            }
            set {
                this.rEC_IDField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_ZONE_ID {
            get {
                return this.cEN_ZONE_IDField;
            }
            set {
                this.cEN_ZONE_IDField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_ZONE_SUB_ID {
            get {
                return this.cEN_ZONE_SUB_IDField;
            }
            set {
                this.cEN_ZONE_SUB_IDField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_ACC_TYPE_ID {
            get {
                return this.cEN_ACC_TYPE_IDField;
            }
            set {
                this.cEN_ACC_TYPE_IDField = value;
            }
        }
        
        /// <remarks/>
        
        public int COD_YEAR_ID {
            get {
                return this.cOD_YEAR_IDField;
            }
            set {
                this.cOD_YEAR_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool COD_YEAR_IDSpecified {
            get {
                return this.cOD_YEAR_IDFieldSpecified;
            }
            set {
                this.cOD_YEAR_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public string COD_YEAR_NAME {
            get {
                return this.cOD_YEAR_NAMEField;
            }
            set {
                this.cOD_YEAR_NAMEField = value;
            }
        }
        
        /// <remarks/>
        
        public System.DateTime COD_YEAR_SDT {
            get {
                return this.cOD_YEAR_SDTField;
            }
            set {
                this.cOD_YEAR_SDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool COD_YEAR_SDTSpecified {
            get {
                return this.cOD_YEAR_SDTFieldSpecified;
            }
            set {
                this.cOD_YEAR_SDTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public System.DateTime COD_YEAR_EDT {
            get {
                return this.cOD_YEAR_EDTField;
            }
            set {
                this.cOD_YEAR_EDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool COD_YEAR_EDTSpecified {
            get {
                return this.cOD_YEAR_EDTFieldSpecified;
            }
            set {
                this.cOD_YEAR_EDTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public int CEN_ID_MAIN {
            get {
                return this.cEN_ID_MAINField;
            }
            set {
                this.cEN_ID_MAINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CEN_ID_MAINSpecified {
            get {
                return this.cEN_ID_MAINFieldSpecified;
            }
            set {
                this.cEN_ID_MAINFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_PAD_NO_MAIN {
            get {
                return this.cEN_PAD_NO_MAINField;
            }
            set {
                this.cEN_PAD_NO_MAINField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_INS_ID {
            get {
                return this.cEN_INS_IDField;
            }
            set {
                this.cEN_INS_IDField = value;
            }
        }
        
        /// <remarks/>
        
        public string INS_NAME {
            get {
                return this.iNS_NAMEField;
            }
            set {
                this.iNS_NAMEField = value;
            }
        }
        
        /// <remarks/>
        
        public string INS_SHORT {
            get {
                return this.iNS_SHORTField;
            }
            set {
                this.iNS_SHORTField = value;
            }
        }
        
        /// <remarks/>
        
        public int IS_VOLUME {
            get {
                return this.iS_VOLUMEField;
            }
            set {
                this.iS_VOLUMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IS_VOLUMESpecified {
            get {
                return this.iS_VOLUMEFieldSpecified;
            }
            set {
                this.iS_VOLUMEFieldSpecified = value;
            }
        }
    }
    
  
    public partial class GetCenterListByPAD_Name {
        
        private string cEN_UIDField;
        
        private string cEN_PAD_NOField;
        
        private string cEN_NAMEField;
        
        private int cEN_IDField;
        
        private bool cEN_IDFieldSpecified;
        
        private string rEC_IDField;
        
        private string cEN_ZONE_IDField;
        
        private string cEN_ZONE_SUB_IDField;
        
        private string cEN_ACC_TYPE_IDField;
        
        private int cOD_YEAR_IDField;
        
        private bool cOD_YEAR_IDFieldSpecified;
        
        private string cOD_YEAR_NAMEField;
        
        private System.DateTime cOD_YEAR_SDTField;
        
        private bool cOD_YEAR_SDTFieldSpecified;
        
        private System.DateTime cOD_YEAR_EDTField;
        
        private bool cOD_YEAR_EDTFieldSpecified;
        
        private int cEN_ID_MAINField;
        
        private bool cEN_ID_MAINFieldSpecified;
        
        private string cEN_PAD_NO_MAINField;
        
        private string auditStatusField;
        
        private int iS_VOLUMEField;
        
        private bool iS_VOLUMEFieldSpecified;
        
        /// <remarks/>
        
        public string CEN_UID {
            get {
                return this.cEN_UIDField;
            }
            set {
                this.cEN_UIDField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_PAD_NO {
            get {
                return this.cEN_PAD_NOField;
            }
            set {
                this.cEN_PAD_NOField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_NAME {
            get {
                return this.cEN_NAMEField;
            }
            set {
                this.cEN_NAMEField = value;
            }
        }
        
        /// <remarks/>
        
        public int CEN_ID {
            get {
                return this.cEN_IDField;
            }
            set {
                this.cEN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CEN_IDSpecified {
            get {
                return this.cEN_IDFieldSpecified;
            }
            set {
                this.cEN_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public string REC_ID {
            get {
                return this.rEC_IDField;
            }
            set {
                this.rEC_IDField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_ZONE_ID {
            get {
                return this.cEN_ZONE_IDField;
            }
            set {
                this.cEN_ZONE_IDField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_ZONE_SUB_ID {
            get {
                return this.cEN_ZONE_SUB_IDField;
            }
            set {
                this.cEN_ZONE_SUB_IDField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_ACC_TYPE_ID {
            get {
                return this.cEN_ACC_TYPE_IDField;
            }
            set {
                this.cEN_ACC_TYPE_IDField = value;
            }
        }
        
        /// <remarks/>
        
        public int COD_YEAR_ID {
            get {
                return this.cOD_YEAR_IDField;
            }
            set {
                this.cOD_YEAR_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool COD_YEAR_IDSpecified {
            get {
                return this.cOD_YEAR_IDFieldSpecified;
            }
            set {
                this.cOD_YEAR_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public string COD_YEAR_NAME {
            get {
                return this.cOD_YEAR_NAMEField;
            }
            set {
                this.cOD_YEAR_NAMEField = value;
            }
        }
        
        /// <remarks/>
        
        public System.DateTime COD_YEAR_SDT {
            get {
                return this.cOD_YEAR_SDTField;
            }
            set {
                this.cOD_YEAR_SDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool COD_YEAR_SDTSpecified {
            get {
                return this.cOD_YEAR_SDTFieldSpecified;
            }
            set {
                this.cOD_YEAR_SDTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public System.DateTime COD_YEAR_EDT {
            get {
                return this.cOD_YEAR_EDTField;
            }
            set {
                this.cOD_YEAR_EDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool COD_YEAR_EDTSpecified {
            get {
                return this.cOD_YEAR_EDTFieldSpecified;
            }
            set {
                this.cOD_YEAR_EDTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public int CEN_ID_MAIN {
            get {
                return this.cEN_ID_MAINField;
            }
            set {
                this.cEN_ID_MAINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CEN_ID_MAINSpecified {
            get {
                return this.cEN_ID_MAINFieldSpecified;
            }
            set {
                this.cEN_ID_MAINFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_PAD_NO_MAIN {
            get {
                return this.cEN_PAD_NO_MAINField;
            }
            set {
                this.cEN_PAD_NO_MAINField = value;
            }
        }
        
        /// <remarks/>
        
        public string AuditStatus {
            get {
                return this.auditStatusField;
            }
            set {
                this.auditStatusField = value;
            }
        }
        
        /// <remarks/>
        
        public int IS_VOLUME {
            get {
                return this.iS_VOLUMEField;
            }
            set {
                this.iS_VOLUMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IS_VOLUMESpecified {
            get {
                return this.iS_VOLUMEFieldSpecified;
            }
            set {
                this.iS_VOLUMEFieldSpecified = value;
            }
        }
    }
    
 
    public partial class GetChildCenterList {
        
        private int cEN_IDField;
        
        private bool cEN_IDFieldSpecified;
        
        /// <remarks/>
        
        public int CEN_ID {
            get {
                return this.cEN_IDField;
            }
            set {
                this.cEN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CEN_IDSpecified {
            get {
                return this.cEN_IDFieldSpecified;
            }
            set {
                this.cEN_IDFieldSpecified = value;
            }
        }
    }
    
  
    public partial class GetClientAuthorizations {
        
        private string taskField;
        
        private string permissionField;
        
        /// <remarks/>
        
        public string Task {
            get {
                return this.taskField;
            }
            set {
                this.taskField = value;
            }
        }
        
        /// <remarks/>
        
        public string Permission {
            get {
                return this.permissionField;
            }
            set {
                this.permissionField = value;
            }
        }
    }
    
   
    public partial class GetCompletedVerification {
        
        private string aV_VERIFICATION_MISC_IDField;
        
        /// <remarks/>
        
        public string AV_VERIFICATION_MISC_ID {
            get {
                return this.aV_VERIFICATION_MISC_IDField;
            }
            set {
                this.aV_VERIFICATION_MISC_IDField = value;
            }
        }
    }
    
   
    public partial class GetIns_List {
        
        private string iNS_NAMEField;
        
        private string iNS_IDField;
        
        private string iNS_SHORTField;
        
        /// <remarks/>
        
        public string INS_NAME {
            get {
                return this.iNS_NAMEField;
            }
            set {
                this.iNS_NAMEField = value;
            }
        }
        
        /// <remarks/>
        
        public string INS_ID {
            get {
                return this.iNS_IDField;
            }
            set {
                this.iNS_IDField = value;
            }
        }
        
        /// <remarks/>
        
        public string INS_SHORT {
            get {
                return this.iNS_SHORTField;
            }
            set {
                this.iNS_SHORTField = value;
            }
        }
    }
    
  
    public partial class GetRecord {
        
        private int cEN_IDField;
        
        private bool cEN_IDFieldSpecified;
        
        private string cEN_INS_IDField;
        
        private bool cEN_MAINField;
        
        private bool cEN_MAINFieldSpecified;
        
        private string cEN_UIDField;
        
        private string cEN_BK_PAD_NOField;
        
        private string cEN_PAD_NOField;
        
        private string cEN_REG_NOField;
        
        private string cEN_STATUSField;
        
        private string cEN_NAMEField;
        
        private string cEN_B_NAMEField;
        
        private string cEN_ADD1Field;
        
        private string cEN_ADD2Field;
        
        private string cEN_ADD3Field;
        
        private string cEN_ADD4Field;
        
        private string cEN_CITY_IDField;
        
        private string cEN_DISTRICT_IDField;
        
        private string cEN_STATE_IDField;
        
        private string cEN_CITYField;
        
        private string cEN_DISTRICTField;
        
        private string cEN_STATEField;
        
        private string cEN_COUNTRYField;
        
        private string cEN_PINCODEField;
        
        private string cEN_TEL_NO_1Field;
        
        private string cEN_TEL_NO_2Field;
        
        private string cEN_MOB_NO_1Field;
        
        private string cEN_MOB_NO_2Field;
        
        private string cEN_FAX_NO_1Field;
        
        private string cEN_FAX_NO_2Field;
        
        private string cEN_EMAIL_ID_1Field;
        
        private string cEN_EMAIL_ID_2Field;
        
        private string cEN_WEBSITE_URLField;
        
        private string cEN_ZONE_IDField;
        
        private string cEN_ZONE_SUB_IDField;
        
        private int cEN_CC_IDField;
        
        private bool cEN_CC_IDFieldSpecified;
        
        private string cEN_INCHARGEField;
        
        private string cEN_IN_PAD_NOField;
        
        private System.DateTime cEN_DOSField;
        
        private bool cEN_DOSFieldSpecified;
        
        private string cEN_CON_SCANCODEField;
        
        private System.DateTime rEC_ADD_ONField;
        
        private bool rEC_ADD_ONFieldSpecified;
        
        private string rEC_ADD_BYField;
        
        private System.DateTime rEC_EDIT_ONField;
        
        private bool rEC_EDIT_ONFieldSpecified;
        
        private string rEC_EDIT_BYField;
        
        private int rEC_STATUSField;
        
        private bool rEC_STATUSFieldSpecified;
        
        private System.DateTime rEC_STATUS_ONField;
        
        private bool rEC_STATUS_ONFieldSpecified;
        
        private string rEC_STATUS_BYField;
        
        private string rEC_IDField;
        
        private string cEN_COUNTRY_IDField;
        
        private System.DateTime cEN_CANCELLATION_DATEField;
        
        private bool cEN_CANCELLATION_DATEFieldSpecified;
        
        private int cEN_CITY_INT_IDField;
        
        private bool cEN_CITY_INT_IDFieldSpecified;
        
        private int cEN_DISTRICT_INT_IDField;
        
        private bool cEN_DISTRICT_INT_IDFieldSpecified;
        
        private int cEN_STATE_INT_IDField;
        
        private bool cEN_STATE_INT_IDFieldSpecified;
        
        private int cEN_COUNTRY_INT_IDField;
        
        private bool cEN_COUNTRY_INT_IDFieldSpecified;
        
        /// <remarks/>
        
        public int CEN_ID {
            get {
                return this.cEN_IDField;
            }
            set {
                this.cEN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CEN_IDSpecified {
            get {
                return this.cEN_IDFieldSpecified;
            }
            set {
                this.cEN_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_INS_ID {
            get {
                return this.cEN_INS_IDField;
            }
            set {
                this.cEN_INS_IDField = value;
            }
        }
        
        /// <remarks/>
        
        public bool CEN_MAIN {
            get {
                return this.cEN_MAINField;
            }
            set {
                this.cEN_MAINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CEN_MAINSpecified {
            get {
                return this.cEN_MAINFieldSpecified;
            }
            set {
                this.cEN_MAINFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_UID {
            get {
                return this.cEN_UIDField;
            }
            set {
                this.cEN_UIDField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_BK_PAD_NO {
            get {
                return this.cEN_BK_PAD_NOField;
            }
            set {
                this.cEN_BK_PAD_NOField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_PAD_NO {
            get {
                return this.cEN_PAD_NOField;
            }
            set {
                this.cEN_PAD_NOField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_REG_NO {
            get {
                return this.cEN_REG_NOField;
            }
            set {
                this.cEN_REG_NOField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_STATUS {
            get {
                return this.cEN_STATUSField;
            }
            set {
                this.cEN_STATUSField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_NAME {
            get {
                return this.cEN_NAMEField;
            }
            set {
                this.cEN_NAMEField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_B_NAME {
            get {
                return this.cEN_B_NAMEField;
            }
            set {
                this.cEN_B_NAMEField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_ADD1 {
            get {
                return this.cEN_ADD1Field;
            }
            set {
                this.cEN_ADD1Field = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_ADD2 {
            get {
                return this.cEN_ADD2Field;
            }
            set {
                this.cEN_ADD2Field = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_ADD3 {
            get {
                return this.cEN_ADD3Field;
            }
            set {
                this.cEN_ADD3Field = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_ADD4 {
            get {
                return this.cEN_ADD4Field;
            }
            set {
                this.cEN_ADD4Field = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_CITY_ID {
            get {
                return this.cEN_CITY_IDField;
            }
            set {
                this.cEN_CITY_IDField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_DISTRICT_ID {
            get {
                return this.cEN_DISTRICT_IDField;
            }
            set {
                this.cEN_DISTRICT_IDField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_STATE_ID {
            get {
                return this.cEN_STATE_IDField;
            }
            set {
                this.cEN_STATE_IDField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_CITY {
            get {
                return this.cEN_CITYField;
            }
            set {
                this.cEN_CITYField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_DISTRICT {
            get {
                return this.cEN_DISTRICTField;
            }
            set {
                this.cEN_DISTRICTField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_STATE {
            get {
                return this.cEN_STATEField;
            }
            set {
                this.cEN_STATEField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_COUNTRY {
            get {
                return this.cEN_COUNTRYField;
            }
            set {
                this.cEN_COUNTRYField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_PINCODE {
            get {
                return this.cEN_PINCODEField;
            }
            set {
                this.cEN_PINCODEField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_TEL_NO_1 {
            get {
                return this.cEN_TEL_NO_1Field;
            }
            set {
                this.cEN_TEL_NO_1Field = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_TEL_NO_2 {
            get {
                return this.cEN_TEL_NO_2Field;
            }
            set {
                this.cEN_TEL_NO_2Field = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_MOB_NO_1 {
            get {
                return this.cEN_MOB_NO_1Field;
            }
            set {
                this.cEN_MOB_NO_1Field = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_MOB_NO_2 {
            get {
                return this.cEN_MOB_NO_2Field;
            }
            set {
                this.cEN_MOB_NO_2Field = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_FAX_NO_1 {
            get {
                return this.cEN_FAX_NO_1Field;
            }
            set {
                this.cEN_FAX_NO_1Field = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_FAX_NO_2 {
            get {
                return this.cEN_FAX_NO_2Field;
            }
            set {
                this.cEN_FAX_NO_2Field = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_EMAIL_ID_1 {
            get {
                return this.cEN_EMAIL_ID_1Field;
            }
            set {
                this.cEN_EMAIL_ID_1Field = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_EMAIL_ID_2 {
            get {
                return this.cEN_EMAIL_ID_2Field;
            }
            set {
                this.cEN_EMAIL_ID_2Field = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_WEBSITE_URL {
            get {
                return this.cEN_WEBSITE_URLField;
            }
            set {
                this.cEN_WEBSITE_URLField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_ZONE_ID {
            get {
                return this.cEN_ZONE_IDField;
            }
            set {
                this.cEN_ZONE_IDField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_ZONE_SUB_ID {
            get {
                return this.cEN_ZONE_SUB_IDField;
            }
            set {
                this.cEN_ZONE_SUB_IDField = value;
            }
        }
        
        /// <remarks/>
        
        public int CEN_CC_ID {
            get {
                return this.cEN_CC_IDField;
            }
            set {
                this.cEN_CC_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CEN_CC_IDSpecified {
            get {
                return this.cEN_CC_IDFieldSpecified;
            }
            set {
                this.cEN_CC_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_INCHARGE {
            get {
                return this.cEN_INCHARGEField;
            }
            set {
                this.cEN_INCHARGEField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_IN_PAD_NO {
            get {
                return this.cEN_IN_PAD_NOField;
            }
            set {
                this.cEN_IN_PAD_NOField = value;
            }
        }
        
        /// <remarks/>
        
        public System.DateTime CEN_DOS {
            get {
                return this.cEN_DOSField;
            }
            set {
                this.cEN_DOSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CEN_DOSSpecified {
            get {
                return this.cEN_DOSFieldSpecified;
            }
            set {
                this.cEN_DOSFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_CON_SCANCODE {
            get {
                return this.cEN_CON_SCANCODEField;
            }
            set {
                this.cEN_CON_SCANCODEField = value;
            }
        }
        
        /// <remarks/>
        
        public System.DateTime REC_ADD_ON {
            get {
                return this.rEC_ADD_ONField;
            }
            set {
                this.rEC_ADD_ONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REC_ADD_ONSpecified {
            get {
                return this.rEC_ADD_ONFieldSpecified;
            }
            set {
                this.rEC_ADD_ONFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public string REC_ADD_BY {
            get {
                return this.rEC_ADD_BYField;
            }
            set {
                this.rEC_ADD_BYField = value;
            }
        }
        
        /// <remarks/>
        
        public System.DateTime REC_EDIT_ON {
            get {
                return this.rEC_EDIT_ONField;
            }
            set {
                this.rEC_EDIT_ONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REC_EDIT_ONSpecified {
            get {
                return this.rEC_EDIT_ONFieldSpecified;
            }
            set {
                this.rEC_EDIT_ONFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public string REC_EDIT_BY {
            get {
                return this.rEC_EDIT_BYField;
            }
            set {
                this.rEC_EDIT_BYField = value;
            }
        }
        
        /// <remarks/>
        
        public int REC_STATUS {
            get {
                return this.rEC_STATUSField;
            }
            set {
                this.rEC_STATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REC_STATUSSpecified {
            get {
                return this.rEC_STATUSFieldSpecified;
            }
            set {
                this.rEC_STATUSFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public System.DateTime REC_STATUS_ON {
            get {
                return this.rEC_STATUS_ONField;
            }
            set {
                this.rEC_STATUS_ONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REC_STATUS_ONSpecified {
            get {
                return this.rEC_STATUS_ONFieldSpecified;
            }
            set {
                this.rEC_STATUS_ONFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public string REC_STATUS_BY {
            get {
                return this.rEC_STATUS_BYField;
            }
            set {
                this.rEC_STATUS_BYField = value;
            }
        }
        
        /// <remarks/>
        
        public string REC_ID {
            get {
                return this.rEC_IDField;
            }
            set {
                this.rEC_IDField = value;
            }
        }
        
        /// <remarks/>
        
        public string CEN_COUNTRY_ID {
            get {
                return this.cEN_COUNTRY_IDField;
            }
            set {
                this.cEN_COUNTRY_IDField = value;
            }
        }
        
        /// <remarks/>
        
        public System.DateTime CEN_CANCELLATION_DATE {
            get {
                return this.cEN_CANCELLATION_DATEField;
            }
            set {
                this.cEN_CANCELLATION_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CEN_CANCELLATION_DATESpecified {
            get {
                return this.cEN_CANCELLATION_DATEFieldSpecified;
            }
            set {
                this.cEN_CANCELLATION_DATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public int CEN_CITY_INT_ID {
            get {
                return this.cEN_CITY_INT_IDField;
            }
            set {
                this.cEN_CITY_INT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CEN_CITY_INT_IDSpecified {
            get {
                return this.cEN_CITY_INT_IDFieldSpecified;
            }
            set {
                this.cEN_CITY_INT_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public int CEN_DISTRICT_INT_ID {
            get {
                return this.cEN_DISTRICT_INT_IDField;
            }
            set {
                this.cEN_DISTRICT_INT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CEN_DISTRICT_INT_IDSpecified {
            get {
                return this.cEN_DISTRICT_INT_IDFieldSpecified;
            }
            set {
                this.cEN_DISTRICT_INT_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public int CEN_STATE_INT_ID {
            get {
                return this.cEN_STATE_INT_IDField;
            }
            set {
                this.cEN_STATE_INT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CEN_STATE_INT_IDSpecified {
            get {
                return this.cEN_STATE_INT_IDFieldSpecified;
            }
            set {
                this.cEN_STATE_INT_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public int CEN_COUNTRY_INT_ID {
            get {
                return this.cEN_COUNTRY_INT_IDField;
            }
            set {
                this.cEN_COUNTRY_INT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CEN_COUNTRY_INT_IDSpecified {
            get {
                return this.cEN_COUNTRY_INT_IDFieldSpecified;
            }
            set {
                this.cEN_COUNTRY_INT_IDFieldSpecified = value;
            }
        }
    }
    
 
    public partial class GetSelectCentreList {
        
        private string centreNameField;
        
        private string certificateNoField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string xCEN_ZONE_IDField;
        
        private string xCEN_ZONE_SUB_IDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Centre Name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CentreName {
            get {
                return this.centreNameField;
            }
            set {
                this.centreNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Certificate No", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CertificateNo {
            get {
                return this.certificateNoField;
            }
            set {
                this.certificateNoField = value;
            }
        }
        
        /// <remarks/>
        
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public string XCEN_ZONE_ID {
            get {
                return this.xCEN_ZONE_IDField;
            }
            set {
                this.xCEN_ZONE_IDField = value;
            }
        }
        
        /// <remarks/>
        
        public string XCEN_ZONE_SUB_ID {
            get {
                return this.xCEN_ZONE_SUB_IDField;
            }
            set {
                this.xCEN_ZONE_SUB_IDField = value;
            }
        }
    }
    
  
    public partial class GetTxnStatusCount {
        
        private string screenField;
        
        private string statusField;
        
        private int cntField;
        
        private bool cntFieldSpecified;
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        /// <remarks/>
        
        public string Screen {
            get {
                return this.screenField;
            }
            set {
                this.screenField = value;
            }
        }
        
        /// <remarks/>
        
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        
        public int Cnt {
            get {
                return this.cntField;
            }
            set {
                this.cntField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CntSpecified {
            get {
                return this.cntFieldSpecified;
            }
            set {
                this.cntFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
            }
        }
    }
    
 
    public partial class Get_Audit_Verifications {
        
        private string nameField;
        
        private string recIDField;
        
        /// <remarks/>
        
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        
        public string RecID {
            get {
                return this.recIDField;
            }
            set {
                this.recIDField = value;
            }
        }
    }
    
  
    public partial class Get_Base_OpenEventId {
        
        private int cas_event_idField;
        
        private bool cas_event_idFieldSpecified;
        
        /// <remarks/>
        
        public int cas_event_id {
            get {
                return this.cas_event_idField;
            }
            set {
                this.cas_event_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cas_event_idSpecified {
            get {
                return this.cas_event_idFieldSpecified;
            }
            set {
                this.cas_event_idFieldSpecified = value;
            }
        }
    }
}
