//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Connectone.Center_Purpose {
    using System.Xml.Serialization;
    
    
    public partial class GetClientAuthorizations {
        
        private string taskField;
        
        private string permissionField;
        
        /// <remarks/>
        
        public string Task {
            get {
                return this.taskField;
            }
            set {
                this.taskField = value;
            }
        }
        
        /// <remarks/>
        
        public string Permission {
            get {
                return this.permissionField;
            }
            set {
                this.permissionField = value;
            }
        }
    }
    
   
    public partial class GetList {
        
        private string purposeField;
        
        private bool activeField;
        
        private bool activeFieldSpecified;
        
        private System.DateTime addOnField;
        
        private bool addOnFieldSpecified;
        
        private string idField;
        
        private string addByField;
        
        private System.DateTime addDateField;
        
        private bool addDateFieldSpecified;
        
        private string editByField;
        
        private System.DateTime editDateField;
        
        private bool editDateFieldSpecified;
        
        private string actionStatusField;
        
        private string actionByField;
        
        private System.DateTime actionDateField;
        
        private bool actionDateFieldSpecified;
        
        /// <remarks/>
        
        public string Purpose {
            get {
                return this.purposeField;
            }
            set {
                this.purposeField = value;
            }
        }
        
        /// <remarks/>
        
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActiveSpecified {
            get {
                return this.activeFieldSpecified;
            }
            set {
                this.activeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Add On", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime AddOn {
            get {
                return this.addOnField;
            }
            set {
                this.addOnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AddOnSpecified {
            get {
                return this.addOnFieldSpecified;
            }
            set {
                this.addOnFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Add By", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddBy {
            get {
                return this.addByField;
            }
            set {
                this.addByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Add Date", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime AddDate {
            get {
                return this.addDateField;
            }
            set {
                this.addDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AddDateSpecified {
            get {
                return this.addDateFieldSpecified;
            }
            set {
                this.addDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Edit By", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EditBy {
            get {
                return this.editByField;
            }
            set {
                this.editByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Edit Date", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime EditDate {
            get {
                return this.editDateField;
            }
            set {
                this.editDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EditDateSpecified {
            get {
                return this.editDateFieldSpecified;
            }
            set {
                this.editDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Action Status", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ActionStatus {
            get {
                return this.actionStatusField;
            }
            set {
                this.actionStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Action By", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ActionBy {
            get {
                return this.actionByField;
            }
            set {
                this.actionByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Action Date", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime ActionDate {
            get {
                return this.actionDateField;
            }
            set {
                this.actionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionDateSpecified {
            get {
                return this.actionDateFieldSpecified;
            }
            set {
                this.actionDateFieldSpecified = value;
            }
        }
    }
    
  
    public partial class GetRecord {
        
        private int cPR_CEN_IDField;
        
        private bool cPR_CEN_IDFieldSpecified;
        
        private string cPR_NAMEField;
        
        private bool cPR_ACTIVEField;
        
        private bool cPR_ACTIVEFieldSpecified;
        
        private System.DateTime rEC_ADD_ONField;
        
        private bool rEC_ADD_ONFieldSpecified;
        
        private string rEC_ADD_BYField;
        
        private System.DateTime rEC_EDIT_ONField;
        
        private bool rEC_EDIT_ONFieldSpecified;
        
        private string rEC_EDIT_BYField;
        
        private int rEC_STATUSField;
        
        private bool rEC_STATUSFieldSpecified;
        
        private System.DateTime rEC_STATUS_ONField;
        
        private bool rEC_STATUS_ONFieldSpecified;
        
        private string rEC_STATUS_BYField;
        
        private string rEC_IDField;
        
        /// <remarks/>
        
        public int CPR_CEN_ID {
            get {
                return this.cPR_CEN_IDField;
            }
            set {
                this.cPR_CEN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CPR_CEN_IDSpecified {
            get {
                return this.cPR_CEN_IDFieldSpecified;
            }
            set {
                this.cPR_CEN_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public string CPR_NAME {
            get {
                return this.cPR_NAMEField;
            }
            set {
                this.cPR_NAMEField = value;
            }
        }
        
        /// <remarks/>
        
        public bool CPR_ACTIVE {
            get {
                return this.cPR_ACTIVEField;
            }
            set {
                this.cPR_ACTIVEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CPR_ACTIVESpecified {
            get {
                return this.cPR_ACTIVEFieldSpecified;
            }
            set {
                this.cPR_ACTIVEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public System.DateTime REC_ADD_ON {
            get {
                return this.rEC_ADD_ONField;
            }
            set {
                this.rEC_ADD_ONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REC_ADD_ONSpecified {
            get {
                return this.rEC_ADD_ONFieldSpecified;
            }
            set {
                this.rEC_ADD_ONFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public string REC_ADD_BY {
            get {
                return this.rEC_ADD_BYField;
            }
            set {
                this.rEC_ADD_BYField = value;
            }
        }
        
        /// <remarks/>
        
        public System.DateTime REC_EDIT_ON {
            get {
                return this.rEC_EDIT_ONField;
            }
            set {
                this.rEC_EDIT_ONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REC_EDIT_ONSpecified {
            get {
                return this.rEC_EDIT_ONFieldSpecified;
            }
            set {
                this.rEC_EDIT_ONFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public string REC_EDIT_BY {
            get {
                return this.rEC_EDIT_BYField;
            }
            set {
                this.rEC_EDIT_BYField = value;
            }
        }
        
        /// <remarks/>
        
        public int REC_STATUS {
            get {
                return this.rEC_STATUSField;
            }
            set {
                this.rEC_STATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REC_STATUSSpecified {
            get {
                return this.rEC_STATUSFieldSpecified;
            }
            set {
                this.rEC_STATUSFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public System.DateTime REC_STATUS_ON {
            get {
                return this.rEC_STATUS_ONField;
            }
            set {
                this.rEC_STATUS_ONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REC_STATUS_ONSpecified {
            get {
                return this.rEC_STATUS_ONFieldSpecified;
            }
            set {
                this.rEC_STATUS_ONFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public string REC_STATUS_BY {
            get {
                return this.rEC_STATUS_BYField;
            }
            set {
                this.rEC_STATUS_BYField = value;
            }
        }
        
        /// <remarks/>
        
        public string REC_ID {
            get {
                return this.rEC_IDField;
            }
            set {
                this.rEC_IDField = value;
            }
        }
    }
}
