//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Connectone.COD {
    using System.Xml.Serialization;
    
    
    public partial class GetActiveCentersFromSelected {
        
        private string cEN_IDField;
        
        private string cOD_YEAR_IDField;
        
        private string cOD_YEAR_NAMEField;
        
        private System.DateTime cOD_YEAR_SDTField;
        
        private bool cOD_YEAR_SDTFieldSpecified;
        
        private System.DateTime cOD_YEAR_EDTField;
        
        private bool cOD_YEAR_EDTFieldSpecified;
        
        /// <remarks/>
        
        public string CEN_ID {
            get {
                return this.cEN_IDField;
            }
            set {
                this.cEN_IDField = value;
            }
        }
        
        /// <remarks/>
        
        public string COD_YEAR_ID {
            get {
                return this.cOD_YEAR_IDField;
            }
            set {
                this.cOD_YEAR_IDField = value;
            }
        }
        
        /// <remarks/>
        
        public string COD_YEAR_NAME {
            get {
                return this.cOD_YEAR_NAMEField;
            }
            set {
                this.cOD_YEAR_NAMEField = value;
            }
        }
        
        /// <remarks/>
        
        public System.DateTime COD_YEAR_SDT {
            get {
                return this.cOD_YEAR_SDTField;
            }
            set {
                this.cOD_YEAR_SDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool COD_YEAR_SDTSpecified {
            get {
                return this.cOD_YEAR_SDTFieldSpecified;
            }
            set {
                this.cOD_YEAR_SDTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public System.DateTime COD_YEAR_EDT {
            get {
                return this.cOD_YEAR_EDTField;
            }
            set {
                this.cOD_YEAR_EDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool COD_YEAR_EDTSpecified {
            get {
                return this.cOD_YEAR_EDTFieldSpecified;
            }
            set {
                this.cOD_YEAR_EDTFieldSpecified = value;
            }
        }
    }
    
   
    public partial class GetClientAuthorizations {
        
        private string taskField;
        
        private string permissionField;
        
        /// <remarks/>
        
        public string Task {
            get {
                return this.taskField;
            }
            set {
                this.taskField = value;
            }
        }
        
        /// <remarks/>
        
        public string Permission {
            get {
                return this.permissionField;
            }
            set {
                this.permissionField = value;
            }
        }
    }
    
   
    public partial class GetCreatedCentersFromSelected {
        
        private int cEN_IDField;
        
        private bool cEN_IDFieldSpecified;
        
        /// <remarks/>
        
        public int CEN_ID {
            get {
                return this.cEN_IDField;
            }
            set {
                this.cEN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CEN_IDSpecified {
            get {
                return this.cEN_IDFieldSpecified;
            }
            set {
                this.cEN_IDFieldSpecified = value;
            }
        }
    }
    
   
    public partial class GetFinancialYearList {
        
        private string aCC_TYPEField;
        
        private string financialYearField;
        
        private System.DateTime fromField;
        
        private bool fromFieldSpecified;
        
        private System.DateTime toField;
        
        private bool toFieldSpecified;
        
        private string lockField;
        
        private int cOD_YEAR_IDField;
        
        private bool cOD_YEAR_IDFieldSpecified;
        
        /// <remarks/>
        
        public string ACC_TYPE {
            get {
                return this.aCC_TYPEField;
            }
            set {
                this.aCC_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Financial Year", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FinancialYear {
            get {
                return this.financialYearField;
            }
            set {
                this.financialYearField = value;
            }
        }
        
        /// <remarks/>
        
        public System.DateTime From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FromSpecified {
            get {
                return this.fromFieldSpecified;
            }
            set {
                this.fromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public System.DateTime To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ToSpecified {
            get {
                return this.toFieldSpecified;
            }
            set {
                this.toFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public string Lock {
            get {
                return this.lockField;
            }
            set {
                this.lockField = value;
            }
        }
        
        /// <remarks/>
        
        public int COD_YEAR_ID {
            get {
                return this.cOD_YEAR_IDField;
            }
            set {
                this.cOD_YEAR_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool COD_YEAR_IDSpecified {
            get {
                return this.cOD_YEAR_IDFieldSpecified;
            }
            set {
                this.cOD_YEAR_IDFieldSpecified = value;
            }
        }
    }
    
  
    public partial class GetUnAuditedFinalYears {
        
        private System.DateTime fromField;
        
        private bool fromFieldSpecified;
        
        private System.DateTime toField;
        
        private bool toFieldSpecified;
        
        private int cOD_YEAR_IDField;
        
        private bool cOD_YEAR_IDFieldSpecified;
        
        /// <remarks/>
        
        public System.DateTime From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FromSpecified {
            get {
                return this.fromFieldSpecified;
            }
            set {
                this.fromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public System.DateTime To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ToSpecified {
            get {
                return this.toFieldSpecified;
            }
            set {
                this.toFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        
        public int COD_YEAR_ID {
            get {
                return this.cOD_YEAR_IDField;
            }
            set {
                this.cOD_YEAR_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool COD_YEAR_IDSpecified {
            get {
                return this.cOD_YEAR_IDFieldSpecified;
            }
            set {
                this.cOD_YEAR_IDFieldSpecified = value;
            }
        }
    }
}
